# Generated by Django 6.0.5 on 2026-06-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FltrdCybersegChr21Variantes',
            fields=[
                ('id_variante', models.IntegerField(blank=True, db_column='ID_VARIANTE', primary_key=True, serialize=False)),
                ('chrom', models.TextField(blank=True, db_column='CHROM', null=True)),
                ('pos', models.IntegerField(blank=True, db_column='POS', null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('alt', models.TextField(blank=True, db_column='ALT', null=True)),
                ('qual', models.FloatField(blank=True, db_column='QUAL', null=True)),
                ('filter', models.TextField(blank=True, db_column='FILTER', null=True)),
                ('info_dp', models.TextField(blank=True, db_column='INFO_DP', null=True)),
                ('info_gt', models.TextField(blank=True, db_column='INFO_GT', null=True)),
            ],
            options={
                'db_table': 'Fltrd_Cyberseg_chr21_Variantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FltrdCybersegChr21Amostras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amostra', models.TextField(blank=True, db_column='AMOSTRA', null=True)),
                ('gt', models.TextField(blank=True, db_column='GT', null=True)),
                ('af', models.FloatField(blank=True, db_column='AF', null=True)),
                ('dp', models.IntegerField(blank=True, db_column='DP', null=True)),
                ('nivel_sigilo', models.IntegerField(blank=True, db_column='NIVEL_SIGILO', default=1, null=True)),
                ('id_variante', models.ForeignKey(db_column='ID_VARIANTE', on_delete=django.db.models.deletion.CASCADE, to='vcf_viewer.fltrdcybersegchr21variantes')),
            ],
            options={
                'db_table': 'Fltrd_Cyberseg_chr21_Amostras',
                'managed': True,
            },
        ),
    ]
