# Generated by Django 6.0.5 on 2026-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcf_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fltrdcybersegchr21variantes',
            name='qual',
            field=models.DecimalField(blank=True, db_column='QUAL', decimal_places=2, max_digits=10, null=True),
        ),
    ]
